### ISSUE TITLE
Отправка за рубеж через addPackage

### ISSUE THREAD

**Issue by narmiel** [shiptoreps/shiptor-russia-php-api-client#10]
Как отправить посылку за рубеж через библиотеку? Получаю ошибку "Invalid value `string` of field `country` in addPackage" при валидации, т.к. country это Enum который может быть только RU, KZ или BY.

**Comment by Jiaffar** [comment]
Добрый день, если кратко - пока никак. Ближе к новому году выйдет обновление где будет скорее всего реализован метод AddPackageExport (название примерное), позволяющий отправлять посылки на экспорт.
