### ISSUE TITLE
Переодически получаю ошибку 

### ISSUE THREAD

**Issue by narmiel** [shiptoreps/shiptor-russia-php-api-client#13]
![default](https://user-images.githubusercontent.com/3997831/50236483-95530080-03cb-11e9-95aa-a7cd2eeacdd5.png)

Периодически получаю такую ошибку, воспроизвести сложно, по всей видимости это происходит когда апи отвечает ошибкой, метод calculateShipping.

**Comment by Jiaffar** [comment]
Это видимо происходит, когда само API Shiptor посылает в ответ не json с ошибкой, а страницу с ошибкой.

**Comment by Jiaffar** [comment]
В обновлении 1.3.1 ошибка была отловлена и исправлена.
