### ISSUE TITLE
Срок доставки

### ISSUE THREAD

**Issue by besproblem** [shiptoreps/shiptor-russia-php-api-client#14]
Добрый день, как получить срок для конкретной доставки? Вижу для некоторых типов доставок срок в ответе но не вижу метода для его получения.

**Comment by Jiaffar** [comment]
Добрый день. Да, до обновления 1.3.0 получить это поле можно было только вызвав $method->get('days').

В обновлении 1.3.0 добавлены два метода getDays (возвращает срок доставки) и getPriority (возвращает поле priority)
