### ISSUE TITLE
Non-static method ShiptorRussiaApiClient\Client\Core\Lang\Messages::get() should not be called statically

### ISSUE THREAD

**Issue by narmiel** [shiptoreps/shiptor-russia-php-api-client#15]
Ошибка Non-static method ShiptorRussiaApiClient\Client\Core\Lang\Messages::get() should not be called statically

версия 1.3.1

**Comment by Jiaffar** [comment]
В версии 1.3.3, вышедшей сегодня, метод Messages::get стал статическим.
