### ISSUE TITLE
Нельзя добавить и обновить sku

### ISSUE THREAD

**Issue by AndrewRadchenko** [shiptoreps/shiptor-russia-php-api-client#16]
В методе addProduct и editProduct нельзя задать sku (штрихкод). Получается передать только штрихкод магазина, но этого недостаточно. Прошу добавить эти методы

**Comment by Jiaffar** [comment]
Да, действительно в методе addProduct не было такой возможности. В обновлении 1.3.2, вышедшем сегодня, такая возможность появилась. Что касается метода editProduct - к сожалению, возможность изменить sku отсутствует.

**Comment by AndrewRadchenko** [comment]
Можем ли мы тогда полностью удалить все товары, и записать их заново? Как можно массово удалить все товары?

**Comment by Jiaffar** [comment]
Такую операцию лучше произвести через личный кабинет Шиптор вручную, чтобы не столкнуться с ограничением на число запросов к API. Массовое удаление товаров через API невозможно.

По поводу sku -- если указывать это поле при создании товара методом addProduct, оно будет продублировано в поле barcode. В дальнейшем, это поле больше нигде не фигурирует (в частности - ответах на методы addProduct/editProduct/getProduct). А поле barcode, напротив, доступно к изменению в методе editProduct. Возможно в вашем случае и не нужно будет удалять все товары, а достаточно обновить существующие, заполнив в них поле barcode - это поле доступно в выдаче при запросах addProduct/editProduct/getProduct и на него можно будет опираться при обмене данных между вашей системой и Shiptor.
