### ISSUE TITLE
Поддержка Guzzle HTTP ^6.3

### ISSUE THREAD

**Issue by narmiel** [shiptoreps/shiptor-russia-php-api-client#7]
Сабж, планируется ли? Фреймворки и библиотеки сейчас ставят "guzzlehttp/guzzle": "^6.3" в зависимости, из-за чего ваш пакет невозможно установить через composer, если таковая зависимость есть.

**Comment by narmiel** [comment]
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install shiptor-russia/api-client 1.1.6
    - Conclusion: don't install shiptor-russia/api-client 1.1.5
    - Conclusion: don't install shiptor-russia/api-client 1.1.4
    - Conclusion: don't install shiptor-russia/api-client 1.1.3
    - Conclusion: remove guzzlehttp/guzzle 6.3.3
    - Installation request for shiptor-russia/api-client ^1.1 -> satisfiable by shiptor-russia/api-client[1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6].
    - Conclusion: don't install guzzlehttp/guzzle 6.3.3
    - shiptor-russia/api-client 1.1.2 requires guzzlehttp/guzzle ~5.1 -> satisfiable by guzzlehttp/guzzle[5.1.0, 5.2.0, 5.3.0, 5.3.1, 5.3.2, 5.3.3, 5.3.x-dev].
    - Can only install one of: guzzlehttp/guzzle[5.3.1, 6.3.3].
    - Can only install one of: guzzlehttp/guzzle[5.3.2, 6.3.3].
    - Can only install one of: guzzlehttp/guzzle[5.3.3, 6.3.3].
    - Can only install one of: guzzlehttp/guzzle[5.3.x-dev, 6.3.3].
    - Can only install one of: guzzlehttp/guzzle[5.1.0, 6.3.3].
    - Can only install one of: guzzlehttp/guzzle[5.2.0, 6.3.3].
    - Can only install one of: guzzlehttp/guzzle[5.3.0, 6.3.3].
    - Installation request for guzzlehttp/guzzle (locked at 6.3.3) -> satisfiable by guzzlehttp/guzzle[6.3.3].

```

**Comment by vslobodyan** [comment]
Потестируем SDK с версией guzzle 6.3
Посмотрим - возникнут ли проблемы с более современной версией

**Comment by narmiel** [comment]
Спасибо, если тестирование пройдет хорошо, можно добавить зависимость примерно так:
`"guzzlehttp/guzzle": "~5.3.1|~6.0",`
для совместимости с теми, кто юзает версию 5. Так сделано например в [апи гугла ](https://github.com/googleapis/google-api-php-client/blob/master/composer.json#L15)

**Comment by vslobodyan** [comment]
> Сабж, планируется ли? Фреймворки и библиотеки сейчас ставят "guzzlehttp/guzzle": "^6.3" в зависимости, из-за чего ваш пакет невозможно установить через composer, если таковая зависимость есть.

Добавили. Пробуйте.

**Comment by narmiel** [comment]
Мне из композера приходит пока версия 1.1.7

**Comment by Jiaffar** [comment]
Да, packagist тянет с обновлением что-то. Уже вышли версии 1.1.8, 1.1.9 и 1.2.0
Можете заместить в composer.json требование для shiptor-russia/api-client на репозиторий
"repositories":[
        {
            "type": "vcs",
            "url": "https://github.com/esteit/shiptor-russia-php-api-client"
        }
    ]

Тогда у вас всегда будет самая свежая версия.

**Comment by narmiel** [comment]
Вроде все ок, спасибо
