### ISSUE TITLE
Ограничение запросов(3 в сек)

### ISSUE THREAD

**Issue by ezhimakov** [shiptoreps/shiptor-russia-php-api-client#8]
В свете последних изменений с ограничением кол-ва запросов в секунду, будут ли какие то изменения в SDK, например возможность регулирования этого количества или преобразование класса в singleton c единой инстанцией, ставящей запросы в очередь на стороне клиента?

**Comment by vslobodyan** [comment]
Сейчас рассматриваются варианты изменений в SDK в связи с упомянутыми ограничениями.
Планируем реализовать до Нового Года.

**Comment by Jiaffar** [comment]
Вышло обновление 1.2.4 которое добавляет ограничение на число запросов.
