### ISSUE TITLE
Задать параметр additional_service через библиотеку

### ISSUE THREAD

**Issue by narmiel** [shiptoreps/shiptor-russia-php-api-client#9]
Здравствуйте, в документации есть параметр additional_service, в методе [AddPackage](https://shiptor.ru/doc/#api-Shipping-addPackage) который невозможно добавить через библиотеку (setField является protected, а своего метода у этого параметра нет).

**Comment by vslobodyan** [comment]
Добавится в следующем обновлении, после оптимизации запросов.
